"""empty message

Revision ID: b35cf84a6239
Revises: bfb77e570101
Create Date: 2024-03-20 00:53:46.555481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35cf84a6239'
down_revision = 'bfb77e570101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DateOfBirth', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('DateOfBirth')

    # ### end Alembic commands ###
